services:
  - type: web
    name: Staybook
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Staybook
          property: connectionString
