services:
  - type: web
    name: staybook
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        value: postgresql://staybook_db_user:HDdqk52YPsXNv7r3lbtpnLKPIBNybX1s@dpg-d6in92ogjchc73df731g-a/staybook_db
        sync: false
      - key: NODE_ENV
        value: production
        sync: false
